### ISSUE TITLE
starting a new relayer

### ISSUE THREAD

**Issue by PFC-developer** [initia-labs/rapid-relayer#10]
should rapid fetch the current block height on fresh start, or when the current height is say > 1000 blocks away from what is in the config file?

I'm trying to test this, and it seems to be fetching from block #0 (and subsequently failing ) on block #20 ;-(

**Comment by ertemann** [comment]
I think you are supposed to set the height from which it starts looking, adding a feature in the config where it just starts from whatever the current blockheight is would be nice.

Makes for less Configuration required.

**Comment by ALPAC-4** [comment]
Rapid relayer is indexing ibc relate events from block_results. So if you want to handle packet that is generated in certain height, you have to give `startHeight` before the height. After update (https://github.com/initia-labs/rapid-relayer/pull/14) if you remain it empty latest height will automatically set.

**Comment by PFC-developer** [comment]
closing. as PR#14 resolves this
